// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEPID_H
#define DRIVEPID_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"
#include "ctre/Phoenix.h"
#include "AHRS.h"


const int c_accelerate = 0;
const int c_deaccelerate = 1;
const int c_stop = 2;


const double c_calibrationValue = 0;

const double c_straightP = 0.01;
const double c_straightI = 0.0;
const double c_straightD = 0;

const double c_turnP = .03; // P = .004, I = 0, D = .0125
const double c_turnI = 0;
const double c_turnD = 0;

const double kToleranceDegrees = 2.0;


/**
 *
 *
 * @author ExampleAuthor
 */
class DrivePID: public frc::PIDSubsystem {
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::Encoder> leftEncoder;
	std::shared_ptr<frc::Encoder> rightEncoder;
	std::shared_ptr<WPI_TalonSRX> left1;
	std::shared_ptr<WPI_TalonSRX> left2;
	std::shared_ptr<WPI_TalonSRX> left3;
	std::shared_ptr<frc::SpeedControllerGroup> leftDriveGroup;
	std::shared_ptr<WPI_TalonSRX> right1;
	std::shared_ptr<WPI_TalonSRX> right2;
	std::shared_ptr<WPI_TalonSRX> right3;
	std::shared_ptr<frc::SpeedControllerGroup> rightDriveGroup;
	std::shared_ptr<frc::DifferentialDrive> diffDrive;

	AHRS *gyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DrivePID();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
	void TankDrive(double leftJS, double rightJS);
	void ArcadeDrive(double leftJS, double rightJS);
	double GetPIDOutput();
	void Rotate(double heading);

	void DriveDistance(double distance, double power, double heading);
	void DriveAccelerate(double distance, double power, double heading);
	void DriveDeaccelerate(double distance, double power);
	void DriveStop(double distance);
	void DriveStraight(double power, double heading);

	double GetRightEncoder();
	double GetLeftEncoder();
	void ZeroEncoders();
	double GetDistance();
	double GetVelocity();
	void SetDirection(double heading);

	float GetYaw();
	void ZeroYaw();

	void SetPIDs(double kP, double kI, double kD);




	int driveState;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
