// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "CenterRight.h"
#include "SetAngle.h"
#include "AutoDistance.h"
#include "AutoRotate.h"
#include "AutoDriveTimed.h"
#include "SetIntake.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CenterRight::CenterRight() {

	//Drive forward to switch
		AddParallel(new SetAngle(145));
		AddSequential(new AutoDistance(-10, -0.8, 0));
		AddSequential(new AutoRotate(34));
		AddSequential(new AutoDistance(-100, -.8, 34));

		//Prepare and place cube
		AddSequential(new SetIntake(0.7, 0.75));
		AddSequential(new AutoRotate(0));
		AddSequential(new AutoDriveTimed(-0.5, 0, .5));

		//Back up and drive to cube
		AddParallel(new SetAngle(160));
		AddSequential(new AutoRotate(37));
		AddSequential(new AutoDistance(100, 0.8, 37));
		AddSequential(new AutoRotate(0));

		//Acquire cube
		AddSequential(new AutoDistance(-40, -0.5, 0, true));
		AddSequential(new SetIntake(-0.7, 0.75));

		//Drive to switch
		AddSequential(new AutoRotate(37));
		AddSequential(new AutoDistance(-100, -0.8, 37));

		//Place cube
		AddSequential(new AutoDriveTimed(-0.3, 0, 1.25));
		AddSequential(new SetIntake(0.7, 0.75));

}
