// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "SetAngle.h"
#include <math.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

SetAngle::SetAngle(double angle): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::arm.get());

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_angle = angle;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void SetAngle::Initialize() {
	Robot::arm.get()->SetAngle(m_angle);
}

// Called repeatedly when this Command is scheduled to run
void SetAngle::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool SetAngle::IsFinished() {
	if ((fabs (Robot::arm.get()->getCurrentAngle() - m_angle)) < 1) {
		return true;
	}
	else {
		return false;
	}
}

// Called once after isFinished returns true
void SetAngle::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetAngle::Interrupted() {

}
